### PR TITLE
Hodgson 3-4

### PR DESCRIPTION
**Pull request by maijapapaya**
@jaredh159 @Henderjay

### CODE REVIEW

**Comment by maijapapaya** [comment]
My plan was to do all the italics in the normal text at the end in one document, but do them in the footnotes now because it's easier, but somehow I started fixing them in the regular text but then realized what I was doing and stopped, so that's why they aren't complete. 

I saw the lint errors also, but they weren't anything to actually fix, as far as I could tell.

**Comment by maijapapaya** [comment]
And I just remembered about the book titles verses plain italics!!! 😫 I will fix those when I go back and do all the italics for the full document.

**Review by Henderjay — CHANGES_REQUESTED** [review]
Hey Maija, chapter 3 looks good. I think chapter 4 might look a little better with a couple changes. **1)** why don't we use real block quotes for all of the quotations of Elias Hicks (instead of embedded sections). Most of these were taken from published journals and I think we can use the standard block quotes, like this:

[quote, , "Apology, Prop. 7, Sec. 3"]
____
We therefore consider our redemption in a two-fold
respect or state, both of which in their own nature are perfect.
____

**Secondly,** Since there are some narrator comments between most of these quotes, I think it might look a little be better (for consistency sake) to use [offsets] for ALL of the ones between the block quotes of the Hicks quotes. Looks like you used offsets for the ones with one line (which is often the right thing). But here I think we should use offsets for any of the single paragraphs between the block quotes. Does that make sense? Just for the sake of consistency throughout this entire chapter. Let me know if you have questions. Thanks!

**Comment by jaredh159** [comment]
@Henderjay something strange is going on with these lint errors, maybe a bug in Jones.  Ignore the weird quote headers with the lint errors, and deal with anything else you see, then when it's (otherwise) ready to merge, let me know, and i'll clean it up and merge it.

**Comment by Henderjay** [comment]
Ok, these look great Maija. I'm going to have Jared merge them, since there seems to be a bug in the editor right now. 👍🏻

**Comment by jaredh159** [comment]
@Henderjay @maijapapaya merged now, sorry about the funkiness!

**Pull request merged**
